packages:
  - apps/*
  - packages/*

engineStrict: true
strictPeerDependencies: true
saveExact: true
verifyDepsBeforeRun: error

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  '@prisma/engines': true
minimumReleaseAgeExclude:
  - '@orval/angular@8.33.0'
  - '@orval/axios@8.33.0'
  - '@orval/core@8.33.0'
  - '@orval/effect@8.33.0'
  - '@orval/fetch@8.33.0'
  - '@orval/hono@8.33.0'
  - '@orval/mcp@8.33.0'
  - '@orval/mock@8.33.0'
  - '@orval/pinia-colada@8.33.0'
  - '@orval/query@8.33.0'
  - '@orval/solid-start@8.33.0'
  - '@orval/swr@8.33.0'
  - '@orval/zod@8.33.0'
  - orval@8.33.0
